apiVersion: v1
kind: ConfigMap
metadata:
  name: greenops-prometheus-config
  namespace: greenops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: greenops-operator
        static_configs:
          - targets: ['greenops-operator.greenops.svc.cluster.local:9400']
      - job_name: flink-operator
        static_configs:
          - targets: ['flink-operator-webhook-service.greenops.svc.cluster.local:9999']
