watchNamespaces:
  - greenops

operatorHealth:
  port: 8085

metrics:
  port: 9999

defaultConfiguration:
  create: true
  append: true
  flink-conf.yaml: |
    kubernetes.operator.metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    kubernetes.operator.metrics.reporter.prom.port: 9999
    kubernetes.operator.reconcile.interval: 15 s
    kubernetes.operator.savepoint.history.max.age: 24 h
    kubernetes.operator.savepoint.history.max.count: 10

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
