apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: greenops-flink
  namespace: greenops
spec:
  image: flink-s3:1.19
  imagePullPolicy: Never
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: s3://greenops/checkpoints
    state.savepoints.dir: s3://greenops/savepoints
    s3.endpoint: http://seaweedfs.greenops.svc.cluster.local:8333
    s3.path.style.access: "true"
    execution.checkpointing.interval: "10000"
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.EnvironmentVariableCredentialsProvider
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: greenops-flink-pod-template
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: greenops-object-store
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: greenops-object-store
                  key: secretKey
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 1
    upgradeMode: savepoint