version: 2
updates:
  - package-ecosystem: maven
    directory: "/operator"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: pip
    directory: "/telemetry"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: pip
    directory: "/dashboard/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/dashboard"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/operator"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/telemetry"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/dashboard"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: chore
      include: scope
