apiVersion: v2
name: greenops
description: Carbon aware suspension for stateful Apache Flink clusters
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - carbon
  - sustainability
  - flink
  - operator
home: https://github.com/Ergane-Foundation/greenops
sources:
  - https://github.com/Ergane-Foundation/greenops
maintainers:
  - name: Yash Agarwal
    url: https://github.com/yash-agarwa-l
